# The single table of favorite names -- seven characters at most, the width of
# a footswitch label. Both the C code and the descriptor come from here.
#
#     python3 outils/gen_names.py
#
# Ranks are what gets saved: keep the order and the count stable, or a saved
# pedalboard would come back showing a different name.
BASES_NUM = [
    ("CLEAN", 4), ("CRUNCH", 3), ("DRIVE", 4), ("LEAD", 3), ("SOLO", 3),
    ("RHYTHM", 3), ("BOOST", 2), ("FUZZ", 2), ("METAL", 2), ("BLUES", 2),
    ("ROCK", 2), ("FUNK", 2), ("JAZZ", 2), ("TONE", 8), ("AMP", 4),
]

PLAIN = [
    "INTRO", "OUTRO", "VERSE", "CHORUS", "BRIDGE", "BACKING", "ARP",
    "PUNK", "REGGAE", "COUNTRY", "SURF", "GRUNGE", "STONER", "DJENT",
    "SHRED", "GOSPEL",
    "TWEED", "PLEXI", "JCM800", "AC30", "DELUXE", "TWIN", "BASSMAN",
    "PRINCE", "RECTO", "MARK", "JC120", "SUPRO", "HIWATT", "ORANGE",
    "SOLDANO", "FRIEDMN", "DUMBLE", "ZWRECK", "BOGNER", "DIEZEL", "ENGL",
    "MATCHLS", "BADCAT", "SILVER", "BLACKFC", "BROWN",
    "TS808", "TIMMY", "KLON", "BIGMUFF", "OCTAVE", "TREBLE",
    "GRIT", "EDGE", "CHIME", "GLASS", "VELVET", "FAT", "THIN", "SCOOPED",
    "MIDS", "WARM", "BRIGHT", "DARK", "PUNCH", "BITE", "SMOOTH",
]

NAMES = ["AUTO"]

for base, n in BASES_NUM:
    NAMES.append(base)
    for k in range(1, n + 1):
        # a space when there is room for it, glued otherwise: seven at most
        candidate = "%s %d" % (base, k)
        if len(candidate) > 7:
            candidate = "%s%d" % (base, k)
        NAMES.append(candidate)

NAMES += PLAIN

too_long = [n for n in NAMES if len(n) > 7]
assert not too_long, "names too long: %s" % too_long
assert len(NAMES) == len(set(NAMES)), \
    "duplicates: %s" % [n for n in NAMES if NAMES.count(n) > 1]

with open('src/fav_names.h', 'w') as f:
    f.write("/* GENERATED by gen_names.py -- do not edit by hand.\n"
            " * The single table of favorite names, shared by the code and the\n"
            " * descriptor: the only way the two can never drift apart.\n"
            " * Seven characters at most, the width of a footswitch label. */\n"
            "#pragma once\n\n"
            "static const char* const FAV_NAME_TABLE[] = {\n")
    for n in NAMES:
        f.write('\t"%s",\n' % n)
    f.write("};\n\n#define FAV_NAME_COUNT %d\n" % len(NAMES))

print("%d names" % len(NAMES))
print("examples:", ", ".join(NAMES[1:14]))
print("the name ports come out of gen_ports.py, which reads this file back")
